version: '3'
services:
  atlab:
    build:
      context: .
    env_file: /home/${USER}/deploy/.env
    volumes:
      - /tmp/:/tmp/
      - /etc/localtime:/etc/localtime:ro
    ipc: host # needed for multiprocessing (dataloader) in pytorch
