version: '3'

services:

  nsearch7:
    build:
      context: .
      args:
        - nsearch_branch=7.0
    env_file: /home/${USER}/deploy/.env
    volumes:
      - /tmp/:/tmp/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scratch07:/external
      - /home/ewang/nas-project/notebooks/:/notebooks/
    ipc: host # needed for multiprocessing (dataloader) in pytorch
    working_dir: /notebooks

  nsearch7mp:
    build:
      context: .
      args:
        - nsearch_branch=7.0
    env_file: /home/${USER}/deploy/.env
    volumes:
      - /tmp/:/tmp/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scratch07:/external
      - /mnt/lab/users/zheli/:/zheli/
    ipc: host # needed for multiprocessing (dataloader) in pytorch
    working_dir: /zheli

  nsearch8:
    build:
      context: .
      args:
        - nsearch_branch=8.0
    env_file: /home/${USER}/deploy/.env
    volumes:
      - /tmp/:/tmp/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scratch07:/external
      - /home/ewang/nas-project/notebooks/:/notebooks/
    ipc: host # needed for multiprocessing (dataloader) in pytorch
    working_dir: /notebooks

  nsearch8dev:
    build:
      context: .
      args:
        - nsearch_branch=8.0
    env_file: /home/${USER}/deploy/.env
    volumes:
      - /tmp/:/tmp/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scratch07:/external
      - /home/ewang/nas-project/notebooks/:/notebooks/
      - /home/ewang/nas-project/code/attorch:/src/attorch/
      - /home/ewang/nas-project/code/neuro_data:/src/neuro_data/
      - /home/ewang/nas-project/code/network-search-8/:/src/network-search/
    ipc: host # needed for multiprocessing (dataloader) in pytorch
    working_dir: /notebooks
